version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379"
  scrapycompositedemo:
    build: '.'
    image: 'germey/scrapycompositedemo'
    environment:
      ACCOUNTPOOL_URL: 'http://host.docker.internal:6777/antispider7/random'
      PROXYPOOL_URL: 'http://host.docker.internal:5555/random'
      REDIS_HOST: 'redis://redis:6379'
