version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
  scrapycompositedemo:
    build: "."
    image: "germey/scrapycompositedemo"
    environment:
      ACCOUNTPOOL_URL: "http://host.docker.internal:6777/antispider7/random"
      PROXYPOOL_URL: "http://host.docker.internal:5555/random"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
