apiVersion: v1
kind: Service
metadata:
  labels:
    app: scrapycompositedemo
  name: scrapycompositedemo
  namespace: crawler
spec:
  ports:
    - name: "9104"
      port: 9104
      targetPort: 9104
  selector:
    app: scrapycompositedemo
