apiVersion: v1
kind: Service
metadata:
  labels:
    app: scrapycompositedemo
  name: scrapycompositedemo
  namespace: crawler
spec:
  ports:
    - name: "9410"
      port: 9410
      targetPort: 9410
  selector:
    app: scrapycompositedemo
