master:
  persistence:
    size: "10Gi"
  resources:
    limits:
      memory: "1Gi"
      cpu: "300m"
    requests:
      memory: "500Mi"
      cpu: "200m"
slave:
  persistence:
    size: "10Gi"
  resources:
    limits:
      memory: "1Gi"
      cpu: "300m"
    requests:
      memory: "500Mi"
      cpu: "200m"