apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxypool
  name: proxypool
  namespace: crawler
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    app: proxypool
